#!/usr/bin/env bash

export CONTECO_LABEL="package.controlplane_cli - ModEco"
export CONTECO_DESCRIPTION="The CLI controlplane module package."

export CONTECO_TYPE="package"
export CONTECO_NAME="controlplane_cli"
export CONTECO_TAG="v1.0.0"


export CONTECO_BASE="image.wrapper"
export CONTECO_BUILD="modeco"

export MODECO_PACKAGE_UPDATE="latest"
