#!/usr/bin/env bash

##### START MOULE CONFIGURATION KEYVALUES #####
export MODECO_CONTROLPLANE_CLI_COMMAND="'--keepalive:0','.invoke console start-registry'"
export MODECO_CONTROLPLANE_CLI_ENVIRONMENT=""
##### END MOULE CONFIGURATION KEYVALUES #####
